### ISSUE TITLE
Function comparison in splitGroupsRecursivelyAsync

### ISSUE THREAD

**Issue by chenlinj** [davecra/easyEWS#11]
Hi @davecra ,

I traced this issue a while back, implemented the fix already in our custom version of your library, and I just wanted to point it out here to help:

In your `splitGroupsRecursivelyAsync` function [here](https://github.com/davecra/easyEWS/blob/master/easyEws.js#L1106), there are a couple of instances where you do `result.Address` and `item.Address`.

I believe based on your declaration [here](https://github.com/davecra/easyEWS/blob/master/easyEws.js#L1319), `.Address` is a function of `MailboxUser`. And, therefore, when you're doing comparisons like `item.Address == result.Address` or using `indexOf` on it like in [here for example](https://github.com/davecra/easyEWS/blob/master/easyEws.js#L1140), you're really doing a comparison on the functions' pointers/addresses, and not on the email addresses themselves.

I think this should be a minor change, so let me know if you'd like a PR for it or if you'll apply them yourself. Hope it helps!

**Comment by davecra** [comment]
Thank you for the head up on this. I have updated this in the repro and on NPM.

Fixed in 1.0.19.
