### ISSUE TITLE
How to use in NPM project?

### ISSUE THREAD

**Issue by hazcod** [davecra/easyEWS#14]
HI!

A general question, is there a way to use this library while not referencing into `node_modules/`?
I installed it via `nom install easyews` and would like to do a `import easyEws from "easyews";`.
However this returns:

```js
TypeError: undefined is not a function (near '...easyews__WEBPACK_IMPORTED_MODULE_1___default.a.getMailItemMimeContent...')
```

**Comment by davecra** [comment]
Yes, you can point to the JSDELIVR CDN that I use for it. The minified version is here:

<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/easyews/easyEws.min.js"></script>

You can use the script tag, or you can pull it into the package.json into your vendor.js. As for getting the project to recognize it for development, I just import the NPM into NodeModes and add this to the top of the file:

```
/// <reference path="../../node_modules/easyews/easyews.js" />
```

**Comment by davecra** [comment]
`/// <reference path="../../node_modules/easyews/easyews.js" />`
