### ISSUE TITLE
Attachment bigger than 1mb

### ISSUE THREAD

**Issue by adampound** [davecra/easyEWS#20]
Is it possible to send an attachment bigger than 1 MB?

**Comment by davecra** [comment]
Sorry - just now seeing this. The attachment limit is set by the Microsoft OfficeJS makeEwsRequest API and not something that this library can fix, unfortunately. The documentation is [specified here](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/limits-for-activation-and-javascript-api-for-outlook-add-ins):


Exchange Web Services | 1 MB number of characters | mailbox.makeEwsRequestAsync method | Limit for a request or response to a Mailbox.makeEwsRequestAsync call.
-- | -- | -- | --

Exchange Web Services	1 MB number of characters	[mailbox.makeEwsRequestAsync](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/preview-requirement-set/office.context.mailbox#methods) method	Limit for a request or response to a Mailbox.makeEwsRequestAsync call.
