### ISSUE TITLE
Issue with splitGroup on Windows

### ISSUE THREAD

**Issue by davecra** [davecra/easyEWS#3]
Per a report that came to me... 
On Outlook Windows client a group of more than 1500 users fails. It works fine on Mac and web clients. Possible cause might be a the forEach at line 952:

            easyEws.expandGroup(group, function(groupResult) {
                groupResult.forEach(

The forEach across a large group results might cause problems performance wise, memory wise and possibly corrupt the stack. There is a lot more going on in the Windows OfficeJS library than any other platform.

**Comment by davecra** [comment]
Created a test library to see if the forEach is the cause. Converted the foEach to a tranditional for loop.
[easyEws_testBuild.js.txt](https://github.com/davecra/easyEWS/files/4438827/easyEws_testBuild.js.txt)

**Comment by naemcivic** [comment]
Hi David, replacing the forEach has fixed the issue on Outlook 2013. Will need to confirm with a live client today to see if it also fixes the issue on their Windows machine. Will keep you updated, thank you.

**Comment by davecra** [comment]
Updated this fix in v1.0.012.
