### ISSUE TITLE
Missing (error) in try-catch causes MS Edge failure

### ISSUE THREAD

**Issue by vsamtani** [davecra/easyEWS#7]
https://github.com/davecra/easyEWS/blob/60db96e1d475cc01a80421eaab174480fe61a875/easyEws1.0.14.js#L73

should be 

```
} catch (error) {
```

Chrome seems not to mind the missing (error), but MS Edge does.

**Comment by davecra** [comment]
Fixed in easyEws1.0.15.js, staged for next release.
