### ISSUE TITLE
Expanding groups with '&' ampersand in the group

### ISSUE THREAD

**Issue by naemcivic** [davecra/easyEWS#8]
While expanding nested DL which contains ampersand '&' with `splitGroupsAsync()` async would not expand the list correctly.  If a breakpoint was put in at https://github.com/davecra/easyEWS/blob/master/easyEws.js#L504 and escaped the ampersand on the DL  `philip&monkey@test.com -> philip&amp;monkey@test.com`  it returns all the correct recipients.

**Comment by davecra** [comment]
Technically, & should not be supported per this article:
https://docs.microsoft.com/en-us/office365/troubleshoot/active-directory/email-address-contain-underscore

I can add the check to verify. But it seems it might be risky if it already arrives escaped:

```JavaScript
        /** @type {string} */
        var safeGroup = group.replace('&', '&amp;'); // escape properly - just in case
        /** @type {string} */
        var soap =
            '<m:ExpandDL>' +
            '    <m:Mailbox>' +
            '        <t:EmailAddress>' + safeGroup + '</t:EmailAddress>' +
            '    </m:Mailbox>' +
            '</m:ExpandDL>';
```
Considering the & is not considered valid in an email address, is this something one of your customers is encountering or is this just part of your use case testing?

**Comment by davecra** [comment]
NOTE: I will likely do a global “escape” function to clean up the XML just before submission – which I would actually be placed in the asyncEws() call.

**Comment by naemcivic** [comment]
> Considering the & is not considered valid in an email address, is this something one of your customers is encountering or is this just part of your use case testing?

Some of our customers have DLs that contain ampersand as part of the name which poses a problem when trying to expand the list.

**Comment by davecra** [comment]
Fixed in v1.0.16. 

Please confirm let me know if this resolves the issue you were seeing and I will close this out.

**Comment by davecra** [comment]
**NOTE**: I was not able to find a safe way to place this in the *asyncEws()* call. Since that function is central to all of easyEws it would require a full test of all functions to verify and the danger level of breaking something with a dependency there is far too high. So for now this is only fixed in the *expandGroup()* function, which is at the base of *splitGroupsAsync()* and *recursivelySplitGroupsAsync()* functions.

**Comment by naemcivic** [comment]
Hi David,

We have tested this fix on our development and staging environment with positive results, please put a resolution to this issue. Thank you again for providing the fix and suggestion.

**Comment by davecra** [comment]
Closed. Thanks!
