### ISSUE TITLE
sendPlainTextEmailWithAttachment doesn't send the mail and result shows undefined

### ISSUE THREAD

**Issue by kishor1910** [davecra/easyEWS#9]
@davecra @vsamtani  I am able to read the content here via `getMailItemMimeContent` but not able to send mail...result shows `undefined`...could you pls help me with this?
i am trying this example in angular app.
```JS
function sendSuspiciousMessage() {
	var item = Office.context.mailbox.item;
	itemId = item.itemId;
	mailbox = Office.context.mailbox;
	easyEws.getMailItemMimeContent(itemId, function(mimeContent) {
		var toAddress = "securityteam@somwhere.local";
		easyEws.sendPlainTextEmailWithAttachment("Suspicious Email Alert",
							 "A user has forwarded a suspicious email",
							 toAddress,
							 "Suspicious_Email.eml",
							 mimeContent,
							 function(result) { console.log(result); },
							 function(error) { console.log(error); }, 
							 function (debug) { console.log(debug); }
		);
	 }, function(error) { console.log(error); },
	    function(debug) { console.log(debug); } 
	);
}

**Comment by davecra** [comment]
This is an issue with the sendPlainTextEmailWithAttachment function. I have updated the library to correct this issue. Please try again and let me know if this works.

**Comment by davecra** [comment]
Pushed update, pushed to NPM, blogged update [https://theofficecontext.com/2020/07/13/easyews-updated-to-v1-0-17/](https://theofficecontext.com/2020/07/13/easyews-updated-to-v1-0-17/ )

**Comment by davecra** [comment]
Sorry, did not mean to close this yet. Can you please confirm your issue is resolved with this latest build? Then I will close.

**Comment by kishor1910** [comment]
@davecra Thanks much for the quick fix...email send works fine now.

One issue: At receiving mailbox attachment name shows as mail subject, not as attachmentName input param.
this.sendPlainTextEmailWithAttachment = function (subject, body, to, `attachmentName`, attachmentMime, successCallback, errorCallback, debugCallback) 
But at sender's mailbox attachment name shows correctly as given `attachmentName` param. Could you pls check this
or is this expected behavior?

**Comment by vsamtani** [comment]
If the MIME-Type of the attachment is message/rfc822, then Exchange seems to strip out the attachmentName completely when it sends. But the attachmentName is stored in the sent item copy in the sender's mailbox, so it's visible there. 

At the receiving mail system, the name is completely missing. In this situation the mail client typically uses the subject of the message as the name.

So this is not a problem with the code here, but with the behaviour of Exchange when sending that kind of attachment.

**Comment by kishor1910** [comment]
@davecra @vsamtani Thanks for the response...okay will close this, have some issue with moveItem, for that will open another one. Thanks much.
